version: '1.0'

services:
  nogil:
    image: xbit18/python_performance:latest
    privileged: true
    environment:
      - THREADS=$THREADS
      - ITERS=$ITERS
      - IS_HOST_MACOS=$IS_HOST_MACOS
      - DEBUG=$DEBUG
      - VERBOSE=$VERBOSE
      - RESTART=$RESTART
      - TELEGRAM=$TELEGRAM
    volumes:
     - './pyperf_res:/root/pyperf_res'
     - './tests_status:/root/tests_status'