[project]
name = "pyperformance_bm_matrix_multiplication_shared"
requires-python = ">=3.8"
dependencies = ["pyperf"]
urls = {repository = "https://github.com/python/pyperformance"}
version = "0.0.1"

[tool.pyperformance]
name = "matrix_multiplication_shared"